Day 15: Unsupervised Learning & User Segmentation.

In [3]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.datasets import make_blobs
X, _ = make_blobs(n_samples=300, centers=5, cluster_std=0.60, random_state=0)
df = pd.DataFrame(X, columns=['Annual Income', 'Spending Score'])
print("Sample Data:\n", df.head())
scaler = StandardScaler()
X_scaled = scaler.fit_transform(df)

Sample Data:
    Annual Income  Spending Score
0       9.933426       -1.552356
1      -0.571099        8.133061
2       0.559529        4.214007
3       8.464500       -2.788114
4      -1.230659        2.848220


In [13]:
from sklearn.cluster import KMeans
import numpy as np


kmeans= KMeans(n_clusters=3, init='k-means++', random_state=42, n_init=10)
kmeans.fit(X_scaled)

	
kmeans_rand1 = KMeans(n_clusters=3, init='random', random_state=42, n_init=10)
kmeans_rand1.fit(X_scaled)


kmeans_rand2 = KMeans(n_clusters=3, init='random', random_state=99, n_init=10)
kmeans_rand2.fit(X_scaled)

print("Centroids (k-means++):\n", kmeans.cluster_centers_)
print("\nCentroids (random, seed=42):\n", kmeans_rand1.cluster_centers_)
print("\nCentroids (random, seed=99):\n", kmeans_rand2.cluster_centers_)


Centroids (k-means++):
 [[-0.35554377 -0.00572625]
 [ 1.85161805 -1.48057593]
 [-0.76453706  1.42616034]]

Centroids (random, seed=42):
 [[-0.35554377 -0.00572625]
 [-0.76453706  1.42616034]
 [ 1.85161805 -1.48057593]]

Centroids (random, seed=99):
 [[-0.76453706  1.42616034]
 [-0.35554377 -0.00572625]
 [ 1.85161805 -1.48057593]]


In [14]:
diff_1 = np.linalg.norm(kmeans.cluster_centers_ - kmeans_rand1.cluster_centers_)
diff_2 = np.linalg.norm(kmeans.cluster_centers_ - kmeans_rand2.cluster_centers_)

print("\nCentroid Difference (k-means++ vs random-42):", diff_1)
print("Centroid Difference (k-means++ vs random-99):", diff_2)


Centroid Difference (k-means++ vs random-42): 5.530530416780066
Centroid Difference (k-means++ vs random-99): 4.955572920215064


OBSERVATION

The clusters from k-means++ are more stable and consistent.
With random initialization, the centroids change slightly each time.
This shows that K-Means depends on how the initial centroids are chosen.

CONCLUSION 

Using k-means++ gives better results because it picks smarter starting points, making the model more stable, faster, and reliable.

REFLECTION

By using K-Means clustering, we can group users based on similar interests and behavior. For example, if we find a group of users who like late-night events and high-intensity sports, we can use this to improve Mux AI Glass recommendations.

We can show them more events that match their interests, like late-night sports or fitness activities. We can also send notifications at the right time, such as during late hours when they are more active.

Over time, by tracking what they engage with, we can keep improving the recommendations so they stay relevant and useful for the user.